[package]
authors = ["The POG Contributors <contact@pog.network>"]
edition = "2018"
name = "wallet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "wallet"
path = "main.rs"
